version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: skillrefiner-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillrefiner
    ports:
      - "5433:5432"
